version: "3"

services:
  job-portal:
    container_name: job-portal
    image: "job-portal"
    ports:
      - "8080:8080"
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .database.env
      - .redis.env
      - .private.env
      - .public.env
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=updated-job-portal
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  